'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { loadFirewallScope, sample } = require('./helper');

const FS = loadFirewallScope();

function lintIds(name) {
  const { findings } = FS.lint(FS.parse(sample(name)));
  return new Set(findings.map((f) => f.id));
}

// Each known-bad sample must raise (at least) these smells. Asserting a subset
// keeps the test stable if new smells are added later.
const EXPECTED = {
  'iptables-leaky.txt': ['missing-input-drop', 'exposed-admin-port', 'permissive-accept', 'fallthrough-accept'],
  'iptables-shadowed.txt': ['shadowed-rule', 'rule-after-policy-drop'],
  'iptables-portforward.txt': ['exposed-via-dnat'],
  'ufw-status.txt': ['loopback-not-allowed'],
  'iptables-exposed-services.txt': ['exposed-admin-port', 'wide-open-port-range'],
  'iptables-router-sloppy.txt': ['forward-no-default-deny', 'missing-established-accept', 'masquerade-any-source', 'drop-without-log', 'unused-chain'],
  'ip6tables-no-icmpv6.txt': ['icmpv6-blocked'],
};

for (const [name, ids] of Object.entries(EXPECTED)) {
  test(`lint flags [${ids.join(', ')}] in ${name}`, () => {
    const found = lintIds(name);
    for (const id of ids) assert.ok(found.has(id), `expected smell '${id}' in ${name}`);
  });
}

test('lint result carries a numeric counts summary', () => {
  const { counts } = FS.lint(FS.parse(sample('iptables-leaky.txt')));
  for (const k of ['error', 'warning', 'info', 'total']) {
    assert.equal(typeof counts[k], 'number', `counts.${k}`);
  }
  assert.equal(counts.total, counts.error + counts.warning + counts.info);
});

const ALL_SMELLS = [
  'exposed-admin-port',
  'exposed-via-dnat',
  'fallthrough-accept',
  'loopback-not-allowed',
  'missing-input-drop',
  'permissive-accept',
  'rule-after-policy-drop',
  'shadowed-rule',
  'wide-open-port-range',
  'forward-no-default-deny',
  'missing-established-accept',
  'masquerade-any-source',
  'drop-without-log',
  'icmpv6-blocked',
  'unused-chain',
];

test('exposed-via-dnat flags only the admin-port forward, not the web redirect', () => {
  const { findings } = FS.lint(FS.parse(sample('iptables-portforward.txt')));
  const dnat = findings.filter((f) => f.id === 'exposed-via-dnat');
  // The 2222→22 ssh publish is flagged; the 8080→8006 redirect (not an admin
  // port) is not — so exactly one finding, about ssh.
  assert.equal(dnat.length, 1);
  assert.match(dnat[0].title, /ssh/);
});

test('shadowed-rule flags a rule whose CIDR is a subset of an earlier same-action rule', () => {
  const rs = [
    '*filter',
    ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 10.0.0.0/8 -j DROP',
    '-A INPUT -s 10.0.0.5/32 -j DROP',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(findings.some((f) => f.id === 'shadowed-rule'));
});

test('shadowed-rule detects real IPv6 subsets, not just identical text', () => {
  // 2001:db8:0:1::5/128 lives inside 2001:db8::/32, so the /128 rule is dead.
  const rs = [
    '# Generated by ip6tables-save',
    '*filter',
    ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 2001:db8::/32 -j DROP',
    '-A INPUT -s 2001:db8:0:1::5/128 -j DROP',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(
    findings.some((f) => f.id === 'shadowed-rule' && f.ruleIdx === 1),
    'the /128 inside the /32 should be shadowed',
  );
});

test('shadowed-rule does NOT flag an IPv6 address outside the earlier prefix', () => {
  // 2001:dead::5 is not inside 2001:db8::/32 — different traffic, not shadowed.
  const rs = [
    '# Generated by ip6tables-save',
    '*filter',
    ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 2001:db8::/32 -j DROP',
    '-A INPUT -s 2001:dead::5/128 -j DROP',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(!findings.some((f) => f.id === 'shadowed-rule'));
});

test('exposed-admin-port covers data/admin services beyond ssh', () => {
  const { findings } = FS.lint(FS.parse(sample('iptables-exposed-services.txt')));
  const exposed = findings.filter((f) => f.id === 'exposed-admin-port');
  const services = exposed.map((f) => f.title);
  // Each authless / high-value service accepted from 0.0.0.0/0 is flagged.
  for (const svc of ['docker-api', 'elasticsearch', 'memcached', 'smb', 'mssql']) {
    assert.ok(services.some((t) => t.includes(svc)), `expected ${svc} flagged`);
  }
  // VNC is only allowed from 10.0.0.0/8, so it must NOT be flagged as exposed.
  assert.ok(!services.some((t) => t.includes('vnc')), 'vnc is source-restricted, not exposed');
});

test('wide-open-port-range flags a huge dport range but not an ordinary one', () => {
  const { findings } = FS.lint(FS.parse(sample('iptables-exposed-services.txt')));
  const wide = findings.filter((f) => f.id === 'wide-open-port-range');
  // The 1024:65535 rule (64512 ports) is flagged...
  assert.equal(wide.length, 1);
  assert.match(wide[0].title, /64512 ports/);

  // ...but a few-hundred-port app range from any source is not.
  const rs = [
    '*filter', ':INPUT ACCEPT [0:0]',
    '-A INPUT -p tcp -m tcp --dport 8000:8200 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('wide-open-port-range'), '201 ports is not "wide"');
});

test('the sample set exercises every smell', () => {
  const seen = new Set();
  for (const name of Object.keys(EXPECTED)) {
    for (const id of lintIds(name)) seen.add(id);
  }
  for (const id of ALL_SMELLS) {
    assert.ok(seen.has(id), `no sample triggers '${id}'`);
  }
});

test('missing-established-accept does NOT fire when the conntrack rule exists', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('missing-established-accept'));
});

test('missing-established-accept is skipped for ufw (backend adds it invisibly)', () => {
  // Deny posture, no conntrack rule visible — exactly what `ufw status` shows.
  const ids = lintIds('ufw-status.txt');
  assert.ok(!ids.has('missing-established-accept'));
});

test('forward-no-default-deny stays quiet on policy DROP or a catch-all tail', () => {
  const dropPolicy = [
    '*filter', ':FORWARD DROP [0:0]', 'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(dropPolicy)).findings.map((f) => f.id)).has('forward-no-default-deny'));

  const catchAll = [
    '*filter', ':FORWARD ACCEPT [0:0]',
    '-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    '-A FORWARD -j DROP',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(catchAll)).findings.map((f) => f.id)).has('forward-no-default-deny'));
});

test('masquerade-any-source stays quiet when the source is restricted', () => {
  const rs = [
    '*nat', ':POSTROUTING ACCEPT [0:0]',
    '-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('masquerade-any-source'));
});

test('masquerade-any-source flags an unrestricted nft masquerade, not a saddr-scoped one', () => {
  const flagged = [
    'table ip nat {',
    '	chain postrouting {',
    '		type nat hook postrouting priority srcnat; policy accept;',
    '		oifname "eth0" masquerade',
    '	}',
    '}',
  ].join('\n');
  assert.ok(new Set(FS.lint(FS.parse(flagged)).findings.map((f) => f.id)).has('masquerade-any-source'));

  const scoped = [
    'table ip nat {',
    '	chain postrouting {',
    '		type nat hook postrouting priority srcnat; policy accept;',
    '		ip saddr 10.8.0.0/24 oifname "eth0" masquerade',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(scoped)).findings.map((f) => f.id)).has('masquerade-any-source'));
});

test('drop-without-log stays quiet when a LOG rule exists, and is skipped for ufw', () => {
  const logged = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "DROP-INPUT: "',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(logged)).findings.map((f) => f.id)).has('drop-without-log'));

  // ufw's backend logs on its own; `ufw status` can't show it — never flag.
  assert.ok(!lintIds('ufw-status.txt').has('drop-without-log'));
});

test('drop-without-log recognizes the nft log statement (not just -j LOG)', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		log prefix "DROP-INPUT: "',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id)).has('drop-without-log'));
});

test('drop-without-log fires as info on a silent default-deny', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const f = findings.find((x) => x.id === 'drop-without-log');
  assert.ok(f, 'expected drop-without-log');
  assert.equal(f.severity, 'info');
});

test('icmpv6-blocked stays quiet when ICMPv6 is accepted (even via a jumped chain)', () => {
  // Direct accept — the known-good ip6tables sample has `-p ipv6-icmp -j ACCEPT`.
  assert.ok(!lintIds('ip6tables-save.txt').has('icmpv6-blocked'));

  // Accept behind a user-chain jump must count too.
  const jumped = [
    '# Generated by ip6tables-save',
    '*filter',
    ':INPUT DROP [0:0]',
    ':ICMP6 - [0:0]',
    '-A INPUT -j ICMP6',
    '-A ICMP6 -p ipv6-icmp -j ACCEPT',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(jumped)).findings.map((f) => f.id)).has('icmpv6-blocked'));
});

test('icmpv6-blocked never fires on IPv4-only or ufw rulesets', () => {
  // Plain iptables says nothing about the host's IPv6 posture.
  assert.ok(!lintIds('iptables-leaky.txt').has('icmpv6-blocked'));
  assert.ok(!lintIds('iptables-router-sloppy.txt').has('icmpv6-blocked'));
  // ufw's before6.rules accepts ICMPv6 invisibly.
  assert.ok(!lintIds('ufw-status.txt').has('icmpv6-blocked'));
});

test('icmpv6-blocked fires on an nft inet input that drops without an ICMPv6 accept', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		iifname "lo" accept',
    '		ct state established,related accept',
    '		tcp dport 22 accept',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const f = findings.find((x) => x.id === 'icmpv6-blocked');
  assert.ok(f, 'expected icmpv6-blocked');
  assert.equal(f.severity, 'error');
});

test('icmpv6-blocked recognizes the nft `ip6 nexthdr icmpv6` spelling', () => {
  // The flagship nft sample allows ICMPv6 that way — must stay clean.
  assert.ok(!lintIds('nft-ruleset.txt').has('icmpv6-blocked'));

  // An ip-family (IPv4-only) nft table is never flagged.
  const v4only = [
    'table ip filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		ct state established,related accept',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(v4only)).findings.map((f) => f.id)).has('icmpv6-blocked'));
});

test('unused-chain is a warning with rules, info when empty, quiet when referenced', () => {
  const rs = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':WIRED - [0:0]',
    ':ORPHAN - [0:0]',
    ':EMPTY - [0:0]',
    '-A INPUT -j WIRED',
    '-A WIRED -p tcp --dport 443 -j ACCEPT',
    '-A ORPHAN -s 192.168.0.0/16 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const unused = findings.filter((f) => f.id === 'unused-chain');
  // JSON compare: the linter runs in a vm sandbox, so its arrays have a
  // different Array.prototype and deepStrictEqual rejects them cross-realm.
  assert.equal(
    JSON.stringify(unused.map((f) => [f.chain, f.severity]).sort()),
    JSON.stringify([['EMPTY', 'info'], ['ORPHAN', 'warning']]),
  );
});

test('unused-chain flags a chain referenced only by another dead chain', () => {
  const rs = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':DEAD_A - [0:0]',
    ':DEAD_B - [0:0]',
    '-A DEAD_A -j DEAD_B',
    '-A DEAD_B -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const unused = findings.filter((f) => f.id === 'unused-chain').map((f) => f.chain).sort();
  assert.equal(JSON.stringify(unused), JSON.stringify(['DEAD_A', 'DEAD_B']));
});

test('unused-chain stays quiet on the flagship samples (all chains wired)', () => {
  assert.ok(!lintIds('iptables-save.txt').has('unused-chain'));
  assert.ok(!lintIds('nft-ruleset.txt').has('unused-chain'));
  assert.ok(!lintIds('ufw-status.txt').has('unused-chain'));
});

test('unused-chain works for nftables chains without a hook', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		jump wired',
    '	}',
    '	chain wired {',
    '		tcp dport 22 accept',
    '	}',
    '	chain orphan {',
    '		tcp dport 8080 accept',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const unused = findings.filter((f) => f.id === 'unused-chain');
  assert.equal(unused.length, 1);
  assert.equal(unused[0].chain, 'orphan');
});

test('nft forward hook with policy accept is flagged too', () => {
  const rs = [
    'table inet filter {',
    '	chain forward {',
    '		type filter hook forward priority filter; policy accept;',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(findings.some((f) => f.id === 'forward-no-default-deny'));
});
