'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { loadFirewallScope, sample } = require('./helper');

const FS = loadFirewallScope();

function lintIds(name) {
  const { findings } = FS.lint(FS.parse(sample(name)));
  return new Set(findings.map((f) => f.id));
}

// Each known-bad sample must raise (at least) these smells. Asserting a subset
// keeps the test stable if new smells are added later.
const EXPECTED = {
  'iptables-leaky.txt': ['missing-input-drop', 'exposed-admin-port', 'permissive-accept', 'fallthrough-accept'],
  'iptables-shadowed.txt': ['shadowed-rule', 'rule-after-policy-drop'],
  'iptables-portforward.txt': ['exposed-via-dnat', 'unlimited-log', 'unlimited-icmp-echo'],
  'ufw-status.txt': ['loopback-not-allowed', 'unrestricted-egress'],
  'iptables-exposed-services.txt': ['exposed-admin-port', 'wide-open-port-range', 'overbroad-source-trust'],
  'iptables-router-sloppy.txt': ['forward-no-default-deny', 'missing-established-accept', 'masquerade-any-source', 'drop-without-log', 'missing-invalid-drop', 'unused-chain', 'duplicate-rule', 'unlimited-icmp-echo', 'unrestricted-egress', 'mac-based-trust', 'admin-port-no-rate-limit'],
  'ip6tables-no-icmpv6.txt': ['icmpv6-blocked', 'unlimited-log'],
};

for (const [name, ids] of Object.entries(EXPECTED)) {
  test(`lint flags [${ids.join(', ')}] in ${name}`, () => {
    const found = lintIds(name);
    for (const id of ids) assert.ok(found.has(id), `expected smell '${id}' in ${name}`);
  });
}

test('lint result carries a numeric counts summary', () => {
  const { counts } = FS.lint(FS.parse(sample('iptables-leaky.txt')));
  for (const k of ['error', 'warning', 'info', 'total']) {
    assert.equal(typeof counts[k], 'number', `counts.${k}`);
  }
  assert.equal(counts.total, counts.error + counts.warning + counts.info);
});

const ALL_SMELLS = [
  'exposed-admin-port',
  'exposed-via-dnat',
  'fallthrough-accept',
  'loopback-not-allowed',
  'missing-input-drop',
  'permissive-accept',
  'rule-after-policy-drop',
  'shadowed-rule',
  'wide-open-port-range',
  'overbroad-source-trust',
  'forward-no-default-deny',
  'missing-established-accept',
  'masquerade-any-source',
  'drop-without-log',
  'missing-invalid-drop',
  'icmpv6-blocked',
  'unused-chain',
  'unlimited-log',
  'duplicate-rule',
  'unlimited-icmp-echo',
  'unrestricted-egress',
  'mac-based-trust',
  'admin-port-no-rate-limit',
];

test('exposed-via-dnat flags only the admin-port forward, not the web redirect', () => {
  const { findings } = FS.lint(FS.parse(sample('iptables-portforward.txt')));
  const dnat = findings.filter((f) => f.id === 'exposed-via-dnat');
  // The 2222→22 ssh publish is flagged; the 8080→8006 redirect (not an admin
  // port) is not — so exactly one finding, about ssh.
  assert.equal(dnat.length, 1);
  assert.match(dnat[0].title, /ssh/);
});

test('shadowed-rule flags a rule whose CIDR is a subset of an earlier same-action rule', () => {
  const rs = [
    '*filter',
    ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 10.0.0.0/8 -j DROP',
    '-A INPUT -s 10.0.0.5/32 -j DROP',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(findings.some((f) => f.id === 'shadowed-rule'));
});

test('shadowed-rule detects real IPv6 subsets, not just identical text', () => {
  // 2001:db8:0:1::5/128 lives inside 2001:db8::/32, so the /128 rule is dead.
  const rs = [
    '# Generated by ip6tables-save',
    '*filter',
    ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 2001:db8::/32 -j DROP',
    '-A INPUT -s 2001:db8:0:1::5/128 -j DROP',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(
    findings.some((f) => f.id === 'shadowed-rule' && f.ruleIdx === 1),
    'the /128 inside the /32 should be shadowed',
  );
});

test('shadowed-rule does NOT flag an IPv6 address outside the earlier prefix', () => {
  // 2001:dead::5 is not inside 2001:db8::/32 — different traffic, not shadowed.
  const rs = [
    '# Generated by ip6tables-save',
    '*filter',
    ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 2001:db8::/32 -j DROP',
    '-A INPUT -s 2001:dead::5/128 -j DROP',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(!findings.some((f) => f.id === 'shadowed-rule'));
});

test('exposed-admin-port covers data/admin services beyond ssh', () => {
  const { findings } = FS.lint(FS.parse(sample('iptables-exposed-services.txt')));
  const exposed = findings.filter((f) => f.id === 'exposed-admin-port');
  const services = exposed.map((f) => f.title);
  // Each authless / high-value service accepted from 0.0.0.0/0 is flagged.
  for (const svc of ['docker-api', 'elasticsearch', 'memcached', 'smb', 'mssql']) {
    assert.ok(services.some((t) => t.includes(svc)), `expected ${svc} flagged`);
  }
  // VNC is only allowed from 10.0.0.0/8, so it must NOT be flagged as exposed.
  assert.ok(!services.some((t) => t.includes('vnc')), 'vnc is source-restricted, not exposed');
});

test('wide-open-port-range flags a huge dport range but not an ordinary one', () => {
  const { findings } = FS.lint(FS.parse(sample('iptables-exposed-services.txt')));
  const wide = findings.filter((f) => f.id === 'wide-open-port-range');
  // The 1024:65535 rule (64512 ports) is flagged...
  assert.equal(wide.length, 1);
  assert.match(wide[0].title, /64512 ports/);

  // ...but a few-hundred-port app range from any source is not.
  const rs = [
    '*filter', ':INPUT ACCEPT [0:0]',
    '-A INPUT -p tcp -m tcp --dport 8000:8200 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('wide-open-port-range'), '201 ports is not "wide"');
});

test('the sample set exercises every smell', () => {
  const seen = new Set();
  for (const name of Object.keys(EXPECTED)) {
    for (const id of lintIds(name)) seen.add(id);
  }
  for (const id of ALL_SMELLS) {
    assert.ok(seen.has(id), `no sample triggers '${id}'`);
  }
});

test('missing-established-accept does NOT fire when the conntrack rule exists', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('missing-established-accept'));
});

test('missing-established-accept is skipped for ufw (backend adds it invisibly)', () => {
  // Deny posture, no conntrack rule visible — exactly what `ufw status` shows.
  const ids = lintIds('ufw-status.txt');
  assert.ok(!ids.has('missing-established-accept'));
});

test('overbroad-source-trust flags huge public ranges, spares private and honest CIDRs', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -s 0.0.0.0/1 -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -s 128.0.0.0/2 -p tcp -m tcp --dport 443 -j ACCEPT',
    '-A INPUT -s 10.0.0.0/8 -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -s 192.168.1.0/24 -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -s 44.0.0.0/9 -p tcp -m tcp --dport 22 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'overbroad-source-trust');
  // The /1 and the public /2 are flagged; the private /8, the /24 and the
  // public /9 (just past the threshold) are not.
  assert.equal(hits.length, 2);
  // JSON round-trip: linter arrays come from the vm sandbox (cross-realm).
  assert.equal(JSON.stringify(hits.map((h) => h.ruleIdx)), '[0,1]');
  assert.equal(hits[0].severity, 'warning');
  assert.match(hits[0].title, /0\.0\.0\.0\/1/);
});

test('overbroad-source-trust understands IPv6: global unicast flagged, ULA and link-local spared', () => {
  const rs = [
    '# Generated by ip6tables-save',
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -s 2000::/3 -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -s fc00::/7 -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -s fe80::/10 -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -s 2001:db8::/32 -p tcp -m tcp --dport 22 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'overbroad-source-trust');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 0, 'only 2000::/3 (all global unicast) is flagged');
});

test('overbroad-source-trust leaves DROP rules and true any-source accepts alone', () => {
  const rs = [
    '*filter', ':INPUT ACCEPT [0:0]',
    '-A INPUT -s 0.0.0.0/1 -j DROP',
    '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  // A broad DROP is caution, not trust; the source-less accept belongs to
  // the any-source smells, not this one.
  assert.ok(!ids.has('overbroad-source-trust'));
});

test('missing-invalid-drop stays quiet when INVALID is dropped before the accepts', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -m conntrack --ctstate INVALID -j DROP',
    '-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('missing-invalid-drop'));
});

test('missing-invalid-drop flags an INVALID drop placed below the accepts', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT',
    '-A INPUT -m conntrack --ctstate INVALID -j DROP',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'missing-invalid-drop');
  assert.equal(hits.length, 1);
  // Points at the misplaced drop itself (rule index 2), not at the chain.
  assert.equal(hits[0].ruleIdx, 2);
  assert.match(hits[0].title, /after its ACCEPT rules/);
});

test('missing-invalid-drop needs an accept a crafted packet could ride', () => {
  // Deny posture but only loopback + conntrack accepts: nothing to ride, no
  // finding — a chain like this is missing-established-accept's business.
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('missing-invalid-drop'));
});

test('missing-invalid-drop understands the nft spelling and is skipped for ufw', () => {
  const clean = [
    'table inet filter {',
    '  chain input {',
    '    type filter hook input priority 0; policy drop;',
    '    iifname "lo" accept',
    '    ct state invalid drop',
    '    ct state established,related accept',
    '    tcp dport 22 accept',
    '  }',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(clean)).findings.map((f) => f.id)).has('missing-invalid-drop'));

  const dirty = clean.replace('    ct state invalid drop\n', '');
  assert.ok(new Set(FS.lint(FS.parse(dirty)).findings.map((f) => f.id)).has('missing-invalid-drop'));

  // ufw's backend drops INVALID in ufw-before-input without ever showing it.
  assert.ok(!lintIds('ufw-status.txt').has('missing-invalid-drop'));
});

test('forward-no-default-deny stays quiet on policy DROP or a catch-all tail', () => {
  const dropPolicy = [
    '*filter', ':FORWARD DROP [0:0]', 'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(dropPolicy)).findings.map((f) => f.id)).has('forward-no-default-deny'));

  const catchAll = [
    '*filter', ':FORWARD ACCEPT [0:0]',
    '-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    '-A FORWARD -j DROP',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(catchAll)).findings.map((f) => f.id)).has('forward-no-default-deny'));
});

test('masquerade-any-source stays quiet when the source is restricted', () => {
  const rs = [
    '*nat', ':POSTROUTING ACCEPT [0:0]',
    '-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('masquerade-any-source'));
});

test('masquerade-any-source flags an unrestricted nft masquerade, not a saddr-scoped one', () => {
  const flagged = [
    'table ip nat {',
    '	chain postrouting {',
    '		type nat hook postrouting priority srcnat; policy accept;',
    '		oifname "eth0" masquerade',
    '	}',
    '}',
  ].join('\n');
  assert.ok(new Set(FS.lint(FS.parse(flagged)).findings.map((f) => f.id)).has('masquerade-any-source'));

  const scoped = [
    'table ip nat {',
    '	chain postrouting {',
    '		type nat hook postrouting priority srcnat; policy accept;',
    '		ip saddr 10.8.0.0/24 oifname "eth0" masquerade',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(scoped)).findings.map((f) => f.id)).has('masquerade-any-source'));
});

test('drop-without-log stays quiet when a LOG rule exists, and is skipped for ufw', () => {
  const logged = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "DROP-INPUT: "',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(logged)).findings.map((f) => f.id)).has('drop-without-log'));

  // ufw's backend logs on its own; `ufw status` can't show it — never flag.
  assert.ok(!lintIds('ufw-status.txt').has('drop-without-log'));
});

test('drop-without-log recognizes the nft log statement (not just -j LOG)', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		log prefix "DROP-INPUT: "',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id)).has('drop-without-log'));
});

test('drop-without-log fires as info on a silent default-deny', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const f = findings.find((x) => x.id === 'drop-without-log');
  assert.ok(f, 'expected drop-without-log');
  assert.equal(f.severity, 'info');
});

test('icmpv6-blocked stays quiet when ICMPv6 is accepted (even via a jumped chain)', () => {
  // Direct accept — the known-good ip6tables sample has `-p ipv6-icmp -j ACCEPT`.
  assert.ok(!lintIds('ip6tables-save.txt').has('icmpv6-blocked'));

  // Accept behind a user-chain jump must count too.
  const jumped = [
    '# Generated by ip6tables-save',
    '*filter',
    ':INPUT DROP [0:0]',
    ':ICMP6 - [0:0]',
    '-A INPUT -j ICMP6',
    '-A ICMP6 -p ipv6-icmp -j ACCEPT',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(jumped)).findings.map((f) => f.id)).has('icmpv6-blocked'));
});

test('icmpv6-blocked never fires on IPv4-only or ufw rulesets', () => {
  // Plain iptables says nothing about the host's IPv6 posture.
  assert.ok(!lintIds('iptables-leaky.txt').has('icmpv6-blocked'));
  assert.ok(!lintIds('iptables-router-sloppy.txt').has('icmpv6-blocked'));
  // ufw's before6.rules accepts ICMPv6 invisibly.
  assert.ok(!lintIds('ufw-status.txt').has('icmpv6-blocked'));
});

test('icmpv6-blocked fires on an nft inet input that drops without an ICMPv6 accept', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		iifname "lo" accept',
    '		ct state established,related accept',
    '		tcp dport 22 accept',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const f = findings.find((x) => x.id === 'icmpv6-blocked');
  assert.ok(f, 'expected icmpv6-blocked');
  assert.equal(f.severity, 'error');
});

test('icmpv6-blocked recognizes the nft `ip6 nexthdr icmpv6` spelling', () => {
  // The flagship nft sample allows ICMPv6 that way — must stay clean.
  assert.ok(!lintIds('nft-ruleset.txt').has('icmpv6-blocked'));

  // An ip-family (IPv4-only) nft table is never flagged.
  const v4only = [
    'table ip filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		ct state established,related accept',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(v4only)).findings.map((f) => f.id)).has('icmpv6-blocked'));
});

test('unused-chain is a warning with rules, info when empty, quiet when referenced', () => {
  const rs = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':WIRED - [0:0]',
    ':ORPHAN - [0:0]',
    ':EMPTY - [0:0]',
    '-A INPUT -j WIRED',
    '-A WIRED -p tcp --dport 443 -j ACCEPT',
    '-A ORPHAN -s 192.168.0.0/16 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const unused = findings.filter((f) => f.id === 'unused-chain');
  // JSON compare: the linter runs in a vm sandbox, so its arrays have a
  // different Array.prototype and deepStrictEqual rejects them cross-realm.
  assert.equal(
    JSON.stringify(unused.map((f) => [f.chain, f.severity]).sort()),
    JSON.stringify([['EMPTY', 'info'], ['ORPHAN', 'warning']]),
  );
});

test('unused-chain flags a chain referenced only by another dead chain', () => {
  const rs = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':DEAD_A - [0:0]',
    ':DEAD_B - [0:0]',
    '-A DEAD_A -j DEAD_B',
    '-A DEAD_B -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const unused = findings.filter((f) => f.id === 'unused-chain').map((f) => f.chain).sort();
  assert.equal(JSON.stringify(unused), JSON.stringify(['DEAD_A', 'DEAD_B']));
});

test('unused-chain stays quiet on the flagship samples (all chains wired)', () => {
  assert.ok(!lintIds('iptables-save.txt').has('unused-chain'));
  assert.ok(!lintIds('nft-ruleset.txt').has('unused-chain'));
  assert.ok(!lintIds('ufw-status.txt').has('unused-chain'));
});

test('unused-chain works for nftables chains without a hook', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		jump wired',
    '	}',
    '	chain wired {',
    '		tcp dport 22 accept',
    '	}',
    '	chain orphan {',
    '		tcp dport 8080 accept',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const unused = findings.filter((f) => f.id === 'unused-chain');
  assert.equal(unused.length, 1);
  assert.equal(unused[0].chain, 'orphan');
});

test('unlimited-log fires on an unthrottled LOG, quiet with -m limit / hashlimit', () => {
  const bare = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -j LOG --log-prefix "IN: "',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(bare));
  const hit = findings.find((f) => f.id === 'unlimited-log');
  assert.ok(hit, 'expected unlimited-log');
  assert.equal(hit.severity, 'warning');
  assert.equal(hit.ruleIdx, 0);

  for (const limited of [
    '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "IN: "',
    '-A INPUT -m hashlimit --hashlimit-above 10/min --hashlimit-name lg -j LOG',
  ]) {
    const rs = ['*filter', ':INPUT DROP [0:0]', limited, 'COMMIT'].join('\n');
    const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
    assert.ok(!ids.has('unlimited-log'), `should be quiet for: ${limited}`);
  }
});

test('unlimited-log understands the nft limit rate statement', () => {
  const flagged = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		log prefix "IN: "',
    '	}',
    '}',
  ].join('\n');
  assert.ok(new Set(FS.lint(FS.parse(flagged)).findings.map((f) => f.id)).has('unlimited-log'));

  const throttled = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		limit rate 5/minute log prefix "IN: "',
    '	}',
    '}',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(throttled)).findings.map((f) => f.id)).has('unlimited-log'));
});

test('unlimited-log stays quiet on the flagship samples (their LOGs are throttled)', () => {
  for (const s of ['iptables-save.txt', 'ip6tables-save.txt', 'nft-ruleset.txt', 'ufw-status.txt']) {
    assert.ok(!lintIds(s).has('unlimited-log'), `expected ${s} clean`);
  }
});

test('duplicate-rule flags the copy, points at the original, and skips near-duplicates', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "IN: "',
    '-A INPUT -p tcp -m tcp --dport 22 -s 10.0.0.0/8 -j ACCEPT',
    '-A INPUT -m limit --limit 5/min -j LOG --log-prefix "IN: "',
    '-A INPUT -p tcp -m tcp --dport 22 -s 10.0.1.0/24 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const dups = findings.filter((f) => f.id === 'duplicate-rule');
  assert.equal(dups.length, 1, 'only the byte-identical LOG copy is a duplicate');
  assert.equal(dups[0].ruleIdx, 2);
  assert.equal(dups[0].duplicateOf, 0);
  assert.equal(dups[0].severity, 'warning');
});

test('an exact terminal copy is duplicate-rule, not shadowed-rule; a subset is still shadowed-rule', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -p tcp -m tcp --dport 22 -s 10.0.0.0/8 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  const dup = findings.filter((f) => f.id === 'duplicate-rule');
  const shadowed = findings.filter((f) => f.id === 'shadowed-rule');
  assert.equal(dup.length, 1);
  assert.equal(dup[0].ruleIdx, 1);
  assert.equal(shadowed.length, 1, 'the narrower rule is shadowing, not duplication');
  assert.equal(shadowed[0].ruleIdx, 2);
});

test('duplicate-rule understands nft rulesets and ignores whitespace differences', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority filter; policy drop;',
    '		limit rate 5/minute log prefix "IN: "',
    '		limit rate 5/minute  log prefix "IN: "',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(findings.some((f) => f.id === 'duplicate-rule'));
});

test('duplicate-rule stays quiet on the flagship samples', () => {
  for (const s of ['iptables-save.txt', 'ip6tables-save.txt', 'nft-ruleset.txt', 'ufw-status.txt', 'iptables-shadowed.txt']) {
    assert.ok(!lintIds(s).has('duplicate-rule'), `expected ${s} clean`);
  }
});

test('nft forward hook with policy accept is flagged too', () => {
  const rs = [
    'table inet filter {',
    '	chain forward {',
    '		type filter hook forward priority filter; policy accept;',
    '	}',
    '}',
  ].join('\n');
  const { findings } = FS.lint(FS.parse(rs));
  assert.ok(findings.some((f) => f.id === 'forward-no-default-deny'));
});

test('unlimited-icmp-echo flags blanket and explicit v4 echo accepts, spares limited/typed/scoped ones', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p icmp -j ACCEPT',
    '-A INPUT -p icmp -m icmp --icmp-type echo-request -j ACCEPT',
    '-A INPUT -p icmp -m limit --limit 10/sec -j ACCEPT',
    '-A INPUT -p icmp -m icmp --icmp-type destination-unreachable -j ACCEPT',
    '-A INPUT -p icmp -s 10.0.0.0/8 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'unlimited-icmp-echo');
  // Blanket icmp (echo included) and explicit echo-request fire; the
  // rate-limited, non-echo-typed and source-scoped accepts do not.
  assert.equal(JSON.stringify(hits.map((h) => h.ruleIdx)), JSON.stringify([0, 1]));
  assert.equal(hits[0].severity, 'info');
});

test('unlimited-icmp-echo reads the nft spellings and respects limit rate', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority 0; policy drop;',
    '		icmp type echo-request accept',
    '		ip protocol icmp limit rate 10/second accept',
    '	}',
    '}',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'unlimited-icmp-echo');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 0);
});

test('unlimited-icmp-echo punishes explicit ICMPv6 echo but never blanket ICMPv6', () => {
  // Blanket ICMPv6 accepts are what icmpv6-blocked demands (Neighbor
  // Discovery, PMTUD) — only an explicit unthrottled echo-request match
  // (type 128) is ping-specific enough to flag.
  const rs = [
    '# Generated by ip6tables-save',
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p ipv6-icmp -j ACCEPT',
    '-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 128 -j ACCEPT',
    '-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type echo-request -m limit --limit 5/sec -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'unlimited-icmp-echo');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 1);
});

test('unlimited-icmp-echo is skipped for ufw', () => {
  const ids = lintIds('ufw-status.txt');
  assert.ok(!ids.has('unlimited-icmp-echo'));
});

test('unrestricted-egress fires when INPUT is locked down and OUTPUT is wide open', () => {
  const rs = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':OUTPUT ACCEPT [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'unrestricted-egress');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].severity, 'info');
  assert.equal(hits[0].chain, 'OUTPUT');
  assert.equal(hits[0].ruleIdx, null);
});

test('unrestricted-egress stays quiet when INPUT is open too (missing-input-drop territory)', () => {
  const rs = [
    '*filter',
    ':INPUT ACCEPT [0:0]',
    ':OUTPUT ACCEPT [0:0]',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('unrestricted-egress'));
  assert.ok(ids.has('missing-input-drop'));
});

test('unrestricted-egress spares an OUTPUT with deny policy or a catch-all deny', () => {
  const policyDeny = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':OUTPUT DROP [0:0]',
    '-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(policyDeny)).findings.map((f) => f.id)).has('unrestricted-egress'));

  const catchAll = [
    '*filter',
    ':INPUT DROP [0:0]',
    ':OUTPUT ACCEPT [0:0]',
    '-A OUTPUT -p udp --dport 53 -j ACCEPT',
    '-A OUTPUT -j DROP',
    'COMMIT',
  ].join('\n');
  assert.ok(!new Set(FS.lint(FS.parse(catchAll)).findings.map((f) => f.id)).has('unrestricted-egress'));
});

test('unrestricted-egress accepts a catch-all-drop INPUT as "locked down"', () => {
  // Deny posture via final catch-all rule instead of chain policy.
  const rs = [
    '*filter',
    ':INPUT ACCEPT [0:0]',
    ':OUTPUT ACCEPT [0:0]',
    '-A INPUT -i lo -j ACCEPT',
    '-A INPUT -j DROP',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'unrestricted-egress');
  assert.equal(hits.length, 1);
});

test('unrestricted-egress reads the nft hooks and spares a deny-posture output', () => {
  const open = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority 0; policy drop;',
    '	}',
    '	chain output {',
    '		type filter hook output priority 0; policy accept;',
    '	}',
    '}',
  ].join('\n');
  const hits = FS.lint(FS.parse(open)).findings.filter((f) => f.id === 'unrestricted-egress');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].chain, 'output');

  const filtered = open.replace('hook output priority 0; policy accept;', 'hook output priority 0; policy drop;');
  assert.ok(!new Set(FS.lint(FS.parse(filtered)).findings.map((f) => f.id)).has('unrestricted-egress'));
});

test('unrestricted-egress fires on the default ufw posture (deny in, allow out)', () => {
  const hits = FS.lint(FS.parse(sample('ufw-status.txt'))).findings.filter((f) => f.id === 'unrestricted-egress');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].chain, 'OUTPUT');
});

test('mac-based-trust flags an ACCEPT keyed on a source MAC, spares a DROP', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p tcp -m tcp --dport 8080 -m mac --mac-source AA:BB:CC:DD:EE:FF -j ACCEPT',
    '-A INPUT -m mac --mac-source 11:22:33:44:55:66 -j DROP',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'mac-based-trust');
  // The trusting ACCEPT fires; blocking a known-bad MAC is caution, not trust.
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 0);
  assert.equal(hits[0].severity, 'warning');
  assert.match(hits[0].title, /AA:BB:CC:DD:EE:FF/);
});

test('mac-based-trust reads the nft ether saddr spelling', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority 0; policy drop;',
    '		ether saddr aa:bb:cc:dd:ee:ff tcp dport 8080 accept',
    '		ether saddr 11:22:33:44:55:66 drop',
    '	}',
    '}',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'mac-based-trust');
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 0);
});

test('mac-based-trust does not double-count and coexists with the IP-level smells', () => {
  // An ssh accept "restricted" by MAC only: exposed-admin-port must STILL
  // fire (a MAC match is not a source restriction) alongside this smell.
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p tcp -m tcp --dport 22 -m mac --mac-source AA:BB:CC:DD:EE:FF -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = FS.lint(FS.parse(rs)).findings.map((f) => f.id);
  assert.equal(ids.filter((x) => x === 'mac-based-trust').length, 1);
  assert.ok(ids.includes('exposed-admin-port'), 'MAC match must not count as a source restriction');
});

test('admin-port-no-rate-limit flags an unthrottled SSH accept, spares a throttled one', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT',
    '-A INPUT -p tcp --dport 22 -m recent --set -j ACCEPT',
    '-A INPUT -p tcp --dport 22 -m hashlimit --hashlimit-name ssh --hashlimit-above 5/min -j ACCEPT',
    '-A INPUT -p tcp --dport 22 -m connlimit --connlimit-above 10 -j DROP',
    'COMMIT',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'admin-port-no-rate-limit');
  // Only the first (bare) accept is flagged; recent/hashlimit ones are throttled,
  // and the connlimit rule is a DROP (not an accept) so it never qualifies.
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 0);
  assert.equal(hits[0].severity, 'info');
  assert.match(hits[0].title, /ssh/);
});

test('admin-port-no-rate-limit ignores non-admin service ports', () => {
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT',
    '-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = new Set(FS.lint(FS.parse(rs)).findings.map((f) => f.id));
  assert.ok(!ids.has('admin-port-no-rate-limit'), 'http/https are not admin ports');
});

test('admin-port-no-rate-limit reads the nft limit rate / ct count spellings', () => {
  const rs = [
    'table inet filter {',
    '	chain input {',
    '		type filter hook input priority 0; policy drop;',
    '		tcp dport 3389 accept',
    '		tcp dport 3306 limit rate 10/minute accept',
    '		tcp dport 5432 ct count over 20 drop',
    '	}',
    '}',
  ].join('\n');
  const hits = FS.lint(FS.parse(rs)).findings.filter((f) => f.id === 'admin-port-no-rate-limit');
  // rdp/3389 bare accept fires; the throttled mysql accept and the ct-count
  // postgres drop do not.
  assert.equal(hits.length, 1);
  assert.equal(hits[0].ruleIdx, 0);
  assert.match(hits[0].title, /rdp/);
});

test('admin-port-no-rate-limit composes with exposed-admin-port (different axes)', () => {
  // An any-source SSH with no throttle: exposed-admin-port (who) AND
  // admin-port-no-rate-limit (how fast) both fire, once each.
  const rs = [
    '*filter', ':INPUT DROP [0:0]',
    '-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT',
    'COMMIT',
  ].join('\n');
  const ids = FS.lint(FS.parse(rs)).findings.map((f) => f.id);
  assert.equal(ids.filter((x) => x === 'admin-port-no-rate-limit').length, 1);
  assert.ok(ids.includes('exposed-admin-port'));
});

test('admin-port-no-rate-limit is skipped for ufw', () => {
  assert.ok(!lintIds('ufw-status.txt').has('admin-port-no-rate-limit'));
});
