(function () {
  'use strict';

  const FORMATS = ['iptables', 'ip6tables', 'nftables', 'ufw'];

  function detectFormat(text) {
    const head = text.slice(0, 4000);

    if (/^Status:\s*(active|inactive)/im.test(head) &&
        /^\s*To\b.*\bAction\b.*\bFrom\b/im.test(head)) {
      return 'ufw';
    }

    if (/^\s*table\s+(inet|ip|ip6|bridge|arp|netdev)\s+\S+\s*\{/m.test(head)) {
      return 'nftables';
    }

    if (/#\s*Generated by ip6tables-save/i.test(head)) {
      return 'ip6tables';
    }

    if (/^\*(filter|nat|mangle|raw|security)\b/m.test(head)) {
      const looksV6 = /\b([0-9a-f]{1,4}:){2,}/i.test(text) &&
                      !/\b\d+\.\d+\.\d+\.\d+\b/.test(text);
      return looksV6 ? 'ip6tables' : 'iptables';
    }

    return null;
  }

  function parse(text, opts) {
    opts = opts || {};
    const format = opts.format || detectFormat(text);

    if (!format) {
      return {
        format: null,
        tables: [],
        warnings: [],
        error: 'Could not detect format. Pick one manually from the dropdown.'
      };
    }

    let result;
    try {
      switch (format) {
        case 'iptables':
          result = window.parseIptablesSave(text, 'iptables');
          break;
        case 'ip6tables':
          result = window.parseIp6tablesSave(text);
          break;
        case 'nftables':
          result = window.parseNftRuleset(text);
          break;
        case 'ufw':
          result = window.parseUfwStatus(text);
          break;
        default:
          return { format: null, tables: [], warnings: [], error: `Unknown format: ${format}` };
      }
    } catch (err) {
      return {
        format,
        tables: [],
        warnings: [],
        error: `Parser failed: ${err.message}`
      };
    }

    result.error = null;
    return result;
  }

  window.FirewallScope = window.FirewallScope || {};
  window.FirewallScope.parse = parse;
  window.FirewallScope.detectFormat = detectFormat;
  window.FirewallScope.FORMATS = FORMATS;
})();
